# Default to using an in-memory DB
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL

---
spring:
  profiles: prod
  datasource:
    url:
    username:
    password:
    driverClassName: org.postgresql.Driver
